language: node_js
node_js: "6"
dist: trusty
sudo: false
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
env:
  - ESHOST_TARGET=node
  - ESHOST_TARGET=firefox
  - ESHOST_TARGET=chakra
  - ESHOST_TARGET=jsshell
  - ESHOST_TARGET=chrome
  - ESHOST_TARGET=remote:firefox
  # ESHOST_REMOTE_WEBDRIVER_SERVER depends on the SAUCE_ACCESS_KEY environment
  # variable. That variable is not available until *after* the TravisCI JWT
  # "plugin" runs., so the WebDriver server URL must be defined within the
  # "install" script.
  - ESHOST_TARGET=remote:edge
    SAUCE_USERNAME=jugglinmike
    ESHOST_WEB_HOST=eshost.test
    ESHOST_REMOTE_WEBDRIVER_SERVER=
  - ESHOST_TARGET=remote:safari
    SAUCE_USERNAME=jugglinmike
    ESHOST_WEB_HOST=eshost.test
    ESHOST_REMOTE_WEBDRIVER_SERVER=
install: |
    export ESHOST_SKIP_D8=1
    export ESHOST_SKIP_JSC=1
    export ESHOST_SKIP_CHROME=1
    export ESHOST_SKIP_FIREFOX=1
    export ESHOST_SKIP_JSSHELL=1
    export ESHOST_SKIP_CH=1
    export ESHOST_SKIP_NODE=1
    export ESHOST_SKIP_REMOTE=1

    function install_firefox {
      export TMP=$(mktemp);
      wget https://archive.mozilla.org/pub/firefox/nightly/2017/07/2017-07-07-10-01-38-mozilla-central/firefox-56.0a1.en-US.linux-x86_64.tar.bz2 -O $TMP;
      tar -xvf $TMP;
      wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz -O $TMP;
      tar --directory firefox -xvf $TMP;
      rm $TMP;
      unset TMP;
    }

    if [[ "$ESHOST_TARGET" == "node" ]]; then
      unset ESHOST_SKIP_NODE;
    elif [[ "$ESHOST_TARGET" == "firefox" ]]; then
      install_firefox;
      export PATH=$(pwd)/firefox:$PATH;
      unset ESHOST_SKIP_FIREFOX;
    elif [[ "$ESHOST_TARGET" == "jsshell" ]]; then
      export TMP=$(mktemp);
      wget https://archive.mozilla.org/pub/firefox/nightly/2017/07/2017-07-07-10-01-38-mozilla-central/jsshell-linux-x86_64.zip -O $TMP;
      mkdir jsshell;
      unzip -d jsshell $TMP;
      rm $TMP;
      unset TMP;
      export PATH=$PATH:$(pwd)/jsshell;
      unset ESHOST_SKIP_JSSHELL;
    elif [[ "$ESHOST_TARGET" == "chakra" ]]; then
      wget https://aka.ms/chakracore/cc_linux_x64_1_5_2;
      tar -xvf cc_linux_x64_1_5_2;
      export PATH=$PATH:$(pwd)/ChakraCoreFiles/bin;
      unset ESHOST_SKIP_CH;
    elif [[ "$ESHOST_TARGET" == "chrome" ]]; then
      channel=unstable
      deb_archive=google-chrome-${channel}_current_amd64.deb
      wget https://dl.google.com/linux/direct/$deb_archive

      # If the environment provides an installation of Google Chrome, the
      # existing binary may take precedence over the one introduced in this
      # script. Remove any previously-existing "alternatives" prior to
      # installation in order to ensure that the new binary is installed as
      # intended.
      if sudo update-alternatives --list google-chrome; then
        sudo update-alternatives --remove-all google-chrome
      fi

      # Installation will fail in cases where the package has unmet dependencies.
      # When this occurs, attempt to use the system package manager to fetch the
      # required packages and retry.
      if ! sudo dpkg --install $deb_archive; then
        sudo apt-get install --fix-broken
        sudo dpkg --install $deb_archive
      fi

      mkdir chrome
      ln -s $(which google-chrome) chrome/chrome

      wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
      unzip -d chrome chromedriver_linux64.zip
      PATH=$PATH:$(pwd)/chrome
      unset ESHOST_SKIP_CHROME;
    elif [[ "$ESHOST_TARGET" == "remote:firefox" ]]; then
      install_firefox;
      wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
      PATH=$PATH:$(pwd)/firefox java -jar selenium-server-standalone-3.4.0.jar &> selenium-server.log &

      export ESHOST_REMOTE_BROWSERNAME=firefox
      export ESHOST_REMOTE_PLATFORM=ANY
      export ESHOST_REMOTE_VERSION=
      unset ESHOST_SKIP_REMOTE;
    elif [[ "$ESHOST_TARGET" == "remote:edge" || "$ESHOST_TARGET" == "remote:safari" ]]; then
      wget https://saucelabs.com/downloads/sc-4.4.8-linux.tar.gz
      tar -xvf sc-4.4.8-linux.tar.gz

      ready_file=sauce-connect-ready-$RANDOM

      sc-4.4.8-linux/bin/sc \
        --logfile=sauce-connect.log \
        --tunnel-domains=eshost.test \
        --tunnel-identifier=$TRAVIS_JOB_NUMBER \
        --no-remove-colliding-tunnels \
        --readyfile=$ready_file &
      SC_PID="$!"

      echo "Waiting for Sauce Connect 'ready' file..."
      while [ ! -f $ready_file ] && ps -f $SC_PID >&/dev/null; do
        sleep .5
      done

      if [ ! -f $ready_file ]; then
        echo "Sauce Connect 'ready' file not created."
        exit 1;
      fi

      echo "Sauce Connect 'ready' file created. Continuing installation."

      if [[ "$ESHOST_TARGET" == "remote:edge" ]]; then
        export ESHOST_REMOTE_BROWSERNAME=MicrosoftEdge
        export ESHOST_REMOTE_PLATFORM='Windows 10'
        export ESHOST_REMOTE_VERSION=15.15063
      elif [[ "$ESHOST_TARGET" == "remote:safari" ]]; then
        export ESHOST_REMOTE_BROWSERNAME=safari
        export ESHOST_REMOTE_PLATFORM='macOS 10.12'
        export ESHOST_REMOTE_VERSION=10.0
      fi

      export ESHOST_REMOTE_WEBDRIVER_SERVER=https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub
      unset ESHOST_SKIP_REMOTE;
    else
      exit 1;
    fi

    npm install
after_script: |
  if [[ "$ESHOST_TARGET" == "remote:firefox" ]]; then
    cat selenium-server.log
  fi

  if [[ "$SC_PID" != "" ]]; then
    echo "Tearing down Sauce Connect tunnel."

    kill $SC_PID

    for i in 0 1 2 3 4 5 6 7 8 9 ; do
      if kill -0 $SC_PID &>/dev/null ; then
        echo "Waiting for Sauce Connect tunnel to exit..."
        sleep 1
      else
        echo "Sauce Connect shutdown complete."
        break
      fi
    done
  fi

  if [ -f sauce-connect.log ]; then
    cat sauce-connect.log
  fi
addons:
  hosts:
    - eshost.test
  # The "jwt" configuration was inserted by the `travis` executable in
  # response to the following command:
  #
  #     travis encrypt  --add addons.jwt SAUCE_ACCESS_KEY=VALUE
  #
  # ...where `VALUE` is the actual access key for the repository owner as
  # provided by Sauce Labs.
  jwt:
    secure: LgoC+2N9gim6lQErlFDM7ALqow1n9EMb3IDLWrBJuUcvedt8RSCZs3oaJJsa4Dz9CAFi9wYLb77fwuqaROQeg1M1EAp20XSaZYCVEZ99AAV+qQJcyzE+ksnsWrDVZr+07XB1MEIClUZn3ZZCoXUUojgMuM/seReKl2bUCVI9LVs3lrtAShFUO7Ovi0L35olfu8LIW4rWltH7oI2I1JoJkA/sXaQDCsOxtegng1W8vptdAb8CFg1mKQMHzMVxx85L50LNk6feXeT9yktfvVCCAqGZqkr89J0Z0YTKX0/NjS1GXyoEUvBEr9CUXF07e5qFhGrvg7BR3QvKUiu86BfHUERzkReUkQ7G76YW3ZlPvJbY9zWdnk4LQpmlsi1KHqq21CZ8wwxcX1MaYHPiRZTvF5+US3VBggJrzkQEUzuxsqmWuVqE655aVct1kbOlKqGgJ8OwUugel3rz90JAEOG4fJD+YpHraxP2rRUFhe7Y1SAj/L5+V168XIx8wrmAKS5X6zmX7AU+hcNknW4gmsPPv5TH3iNY4Nw2gpUx0Er7LS9xywcw2HUyZzFQ7vQcajGyC8yomwnBI2le7Pa9c2ZjoBSWlELZ/ldg/+0VpEEMQz7YLZZNP7f1+4+QuZI6AGMD4EiNn0JH0wFXWHkHjivhS/rqPSuaDsOdABKoX03YyXQ=
